<a href="https://colab.research.google.com/github/spingram/MAT421-sam/blob/main/QR%20factorization%20and%20Linear%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function my_qrfactorization(A) that when given a matrix A returns an Array containg the matrices Q and R from the QR factorization.

In [32]:
import numpy as np

def my_qrfactorization(A):

  rownum = A.shape[0]
  colnum = A.shape[1]
  V = np.zeros((rownum,colnum))
  Q = np.zeros((rownum,colnum))
  for k in range(0,colnum):
    if k == 0:
      V[:,0] = A[:,0]
    else:
      U = A[:,k]
      NewCol = U.copy()
      j= k-1
      while j>=0:
        NewCol = NewCol - ((np.dot(U,V[:,j])/(np.linalg.norm(V[:,j])**2))*V[:,j])
        j = j-1
      V[:,k] = NewCol


  for k in range(0,colnum):
    Q[:,k] = V[:,k]/(np.linalg.norm(V[:,k]))

  R = np.dot((Q.T),A)

  for j in range(0,R.shape[1]):
    for i in range(0,R.shape[0]):
      if (i+j)>(j+j):
        R[i,j]=0


  QR = [Q,R]
  return QR







In [33]:
import numpy as np

A = np.array([[3,5,7],[2,3,9],[7,1,2]])
my_qrfactorization(A)

[array([[ 0.38100038,  0.77095846, -0.51035454],
        [ 0.25400025,  0.44347168,  0.85954449],
        [ 0.88900089, -0.45711696, -0.02686077]]),
 array([[7.87400787, 3.55600356, 6.73100673],
        [0.        , 4.72809039, 8.47372043],
        [0.        , 0.        , 4.10969712]])]

In [34]:
import numpy as np

A = np.array([[3,5],[2,3],[7,1]])
my_qrfactorization(A)

[array([[ 0.38100038,  0.77095846],
        [ 0.25400025,  0.44347168],
        [ 0.88900089, -0.45711696]]),
 array([[7.87400787, 3.55600356],
        [0.        , 4.72809039]])]

In [35]:
import numpy as np

A = np.array([[3,5,7],[2,3,9]])
my_qrfactorization(A)

[array([[ 0.83205029,  0.5547002 ,  0.17378533],
        [ 0.5547002 , -0.83205029, -0.98478356]]),
 array([[ 3.60555128,  5.82435206, 10.81665383],
        [ 0.        ,  0.2773501 , -3.60555128],
        [ 0.        ,  0.        , -7.64655469]])]

Write a program mylinreg that recieves a matrix X with each row being an observation and column a variable, a vector Y with each row being the response to the correspinding observation in X, and a vector Xnew which is a new observation to be added to X. Then returns the coefficients for the variables in X and predicts the respsonse for the new Y

In [71]:
import numpy as np

def mylinreg(X,Y,Xnew):
    rownum = X.shape[0]
    colnum = X.shape[1]
    firstcolumn = np.ones((rownum,1))
    X = np.hstack([firstcolumn,X])
    Y = Y.T
    Beta_hat = np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T,Y))
    Xnew = np.insert(Xnew,0,1)
    Pred = np.dot(Xnew,Beta_hat)
    final = [Beta_hat,Pred]
    return final





In [66]:
X = np.array([[5.6,6.2,6,5.10,5.7,6.5,6.1,5.11,5.5]])
X = X.T
Y = np.array([2,7,4,4,3,10,5,3,3])
X_new = [6]
mylinreg(X,Y,X_new)



[array([-18.25511805,   3.96247949]), 5.519758898637544]

In [72]:
X = np.array([[5.6,8,3],
              [6.2,2,7],
              [6,9,8.8],
              [5.10,5,10],
              [5.7,3,5],
              [6.5,9,4],
              [6.1,5,7],
              [5.11,7,9],
              [5.5,4,5]])
Y = np.array([3,3,13,9,1,10,5,9,3])
X_new = [6,7,6]
mylinreg(X,Y,X_new)

[array([-19.74086347,   1.97571291,   1.18061825,   1.18901251]),
 7.511816890806372]